### ISSUE TITLE
Users never receiving their emails

### ISSUE THREAD

**Issue by eraviart** [CitizensFoundation/your-priorities-app#17]
The emails of our [Your Priorities instance](http://questions.parlement-ouvert.fr/) are not send to their users.

Here is the Systemd file for the workers service (`/etc/systemd/system/your-priorities-workers.service`):

```
[Install]
WantedBy=multi-user.target

[Service]
Environment=DATABASE_URL=postgres://yrpri:secret@localhost/yrpri
Environment=DEBUG=your-priorities-workers
Environment=DEFAULT_HOSTNAME=consultation
Environment="EMAIL_FROM=Parlement ouvert <ne-pas-repondre@parlement-ouvert.fr>"
Environment=ENV=production
Environment=NODE_ENV=production
Environment=REDIS_URL=redis://localhost:6379
Environment=SMTP_SERVER=localhost
Environment=SMTP_PORT=25
Environment=SMTP_ACCEPT_INVALID_CERT=1
ExecStart=/usr/bin/node /home/forteza2017/your-priorities-app/server_api/active-citizen/workers/main.js
Group=forteza2017
Restart=always
StandardOutput=syslog
StandardError=syslog
Type=simple
User=forteza2017
WorkingDirectory=/home/forteza2017/your-priorities-app/server_api

[Unit]
Description=Your-Priorities workers
After=syslog.target network.target
```

The logs after a restart:
```
journalctl -u your-priorities-workers.service

Apr 11 06:37:41 fuchsia systemd[1]: Stopping Your-Priorities workers...
Apr 11 06:37:41 fuchsia systemd[1]: Stopped Your-Priorities workers.
Apr 11 06:37:45 fuchsia systemd[1]: Started Your-Priorities workers.
Apr 11 06:37:48 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":30,"msg":"Starting app access to Kue Queue { redis_url: 'redis://localhost:6379' }","time":"2018-04-11T06:37:
Apr 11 06:37:50 fuchsia node[7663]: SMTP Configured
Apr 11 06:37:50 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":30,"msg":"Dirname { dirname: '/home/forteza2017/your-priorities-app/server_api/active-citizen/workers' }","ti
Apr 11 06:37:51 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":30,"msg":"Have Loaded i18n { err: undefined }","time":"2018-04-11T06:37:51.251Z","v":0}
Apr 11 06:37:51 fuchsia node[7663]: (node:7663) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 job ttl exceeded listeners added. Use emitter.setMaxListeners() to increase limit
Apr 11 06:37:51 fuchsia node[7663]: Server is ready to take our messages
Apr 11 06:37:51 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":30,"msg":"Processing activity Started","time":"2018-04-11T06:37:51.398Z","v":0}
Apr 11 06:37:51 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":30,"msg":"Processing activity Started","time":"2018-04-11T06:37:51.415Z","v":0}
Apr 11 06:37:51 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":30,"msg":"Processing activity Started","time":"2018-04-11T06:37:51.419Z","v":0}
Apr 11 06:37:51 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":30,"msg":"Processing activity Started","time":"2018-04-11T06:37:51.422Z","v":0}
Apr 11 06:37:51 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":30,"msg":"Processing activity Started","time":"2018-04-11T06:37:51.425Z","v":0}
Apr 11 06:37:51 fuchsia node[7663]: (node:7663) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the 
Apr 11 06:37:51 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":50,"msg":"Processing Activity Error { err: 'Activity not found' }","time":"2018-04-11T06:37:51.963Z","v":0}
Apr 11 06:37:52 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":50,"msg":"Processing Activity Error { err: 'Activity not found' }","time":"2018-04-11T06:37:52.011Z","v":0}
Apr 11 06:37:52 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":50,"msg":"Processing Activity Error { err: 'Activity not found' }","time":"2018-04-11T06:37:52.012Z","v":0}
Apr 11 06:37:52 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":50,"msg":"Processing Activity Error { err: 'Activity not found' }","time":"2018-04-11T06:37:52.013Z","v":0}
Apr 11 06:37:52 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":50,"msg":"NotificationNewsFeedWorker Error { err: 'Notification not found' }","time":"2018-04-11T06:37:52.029
Apr 11 06:37:52 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":50,"msg":"NotificationNewsFeedWorker Error { err: 'Notification not found' }","time":"2018-04-11T06:37:52.055
Apr 11 06:37:52 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":50,"msg":"NotificationNewsFeedWorker Error { err: 'Notification not found' }","time":"2018-04-11T06:37:52.055
Apr 11 06:37:52 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":50,"msg":"NotificationNewsFeedWorker Error { err: 'Notification not found' }","time":"2018-04-11T06:37:52.110
Apr 11 06:37:52 fuchsia node[7663]: {"name":"your-priorities","hostname":"fuchsia","pid":7663,"level":30,"msg":"Processing NotificationNewsFeedWorker Started { type: 'notification.point.newsStory',\n  user: \n  
```

The state of the jobs queue:

```javascript
var kue = require('kue');
var queue = kue.createQueue();

queue.activeCount(console.log);
> null 70
queue.inactiveCount(console.log);
> null 9519
queue.failedCount(console.log);
> null 0
queue.delayedCount(console.log);
> null 0
queue.completeCount(console.log);
> null 0
```

Active jobs with `job.type === 'process-activity' && job.data.type === 'activity.password.recovery'`: 0

Inactive jobs with `job.type === 'process-activity' && job.data.type === 'activity.password.recovery'`: 51

Active jobs with `job.type === 'send-one-email'`: 0

Inactive jobs with `job.type === 'send-one-email'`: 0

**Comment by rbjarnason** [comment]
@eraviart Can you try to send a reset password email while the worker is running and see what comes in the log? The "Activity not found" & "Notification not found" point to the Redis queue being out of sync with the database. Can it be that the Redis queue was not cleared between clearing the database after testing during setup?

**Comment by rbjarnason** [comment]
@eraviart Does the worker continue through all those Activity not found & Notification not found errors to iterate over all the 9519 that are still inactive in the queue? Are there errors later to do with the email sending?

**Comment by eraviart** [comment]
Nothing happens in the log when I try a reset password.

What is the best way to synchronize or erase the Redis queue and the events database?

**Comment by eraviart** [comment]
> Does the worker continue through all those Activity not found & Notification not found errors to iterate over all the 9519 that are still inactive in the queue? Are there errors later to do with the email sending?

No it doesn't iterate over the remaining inactive events.

**Comment by rbjarnason** [comment]
@eraviart I guess you could write something for Kue to get everything in sync but the nuclear option is to clear the Redis queue. This would delete any outstanding password reset queries but the links would have expired anyway so probably better not to send them out. Just be careful if you are using the same Redis for the sessions then all live sessions will be deleted when you reset redis so better do it at a time when few people are using the server. https://stackoverflow.com/questions/6851909/how-do-i-delete-everything-in-redis

**Comment by rbjarnason** [comment]
@eraviart After you finish this then I'd keep an eye on the service especially when it comes to failures from connecting to the active citizen predictionio recommendation engine that you are not running but the notification & newsfeed generation systems use this feature. The recommendation code should just return a user error but if you have a problem I will look into it.

**Comment by rbjarnason** [comment]
@eraviart More info - I went through the code testing and found a problem if you are not using AirBrake for collecting errors, this has now been fixed here: https://github.com/CitizensFoundation/active-citizen/commit/f46069a2010f8543ae7863050896cd3dfccb287a

We're are doing final testing on version 7.2 that includes many minor UI fixes, it removes the autotranslation button if its not on the server and another big performance upgrade especially on Edge and IE11. This version will include this AirBrake fix but you can download use it right away if you want it does not conflict with version 7.1

**Comment by eraviart** [comment]
Thanks @rbjarnason.

I tested the _nuclear option_ (ie purging Redis queue) several times, but each time the queue stopped after a few minutes (or hours).

Thanks for you AirBrake fix, I will test it ASAP.

**Comment by rbjarnason** [comment]
@eraviart If you did not have AirBrake then it could be hanging as its not completing callbacks. Is there anything in the log after it stops? I want to get this working 100% even if you don't use AirBrake so I'm here to help.

**Comment by eraviart** [comment]
I confirm that I don't use AirBrake.

I have deployed the latest version of active-citizen. It seems to work (without having to purge Redis queue). But it is too early to be sure. Fingers crossed :-)

**Comment by eraviart** [comment]
It is still working! So I close this ticket. Thanks @rbjarnason.
