### ISSUE TITLE
Problem trying to run the server. Relation "domains" does not exists

### ISSUE THREAD

**Issue by MarceMMAD** [CitizensFoundation/your-priorities-app#2]
I am trying to run the app. I have followed all the installation steps and the server apparently runs and listens on localhost:4242. But when I try to access from the web browser I got this error:

`Unhandled rejection SequelizeDatabaseError: relation "domains" does not exist`

The user validation and connection to the database seems to work properly, but the DB remains empty and no table or data is inserted on it.

Could you help me to solve this issue please?

My OS and software versions are:

- Linux mint 17.3 (based on ubuntu 14.04)
- node.js 6.9.1 (but I have also tried with 7.2.0)
- postgres 9.3

NOTE: I had to run `bower install` command within the `client_api` directory because the `bower.json` file is in that directory.

Thank you. Have a nice day

**Comment by rbjarnason** [comment]
@MarceMMAD Thanks for reporting this. The database was not being created automatically as NOD_ENV was not set to development.  This has been fixed with this commit: https://github.com/rbjarnason/your-priorities-app/commit/fdd352463e4269c8dd147111af8c48af348413a1

**Comment by rbjarnason** [comment]
I also fixed the readme to direct people to the client_app folder.

**Comment by MarceMMAD** [comment]
Thank you very much @rbjarnason  for fixing the problem. It is working now.
