### ISSUE TITLE
bare deploy to heroku -> Unhandled rejection SequelizeDatabaseError: relation "users" does not exist

### ISSUE THREAD

**Issue by Synaccord** [CitizensFoundation/your-priorities-app#36]
I am trying to take this repo and deploy it to heroku,  When I get to the part where I run:
` node server_api/scripts/setAdminOnAll.js`
I get this error:

```
> Unhandled rejection SequelizeDatabaseError: relation "users" does not exist
>     at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
>     at Result.<anonymous> (/app/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
>     at ...
```
Here is exactly what I do from scatch, and after we get it working I'd love to add this to your readme file.  (These are all bash lines - and Markdown doesn't render it correctly). This assumes you have heroku tool belt installed, and that you have the necessary env variables set as described in the comments.

[build-yp.txt](https://github.com/CitizensFoundation/your-priorities-app/files/3402952/build-yp.txt)

I suspect that the hosted postgres service is complaining because the tables don't exist yet.  I work on mongo and have had similar problems moving between services.  If you are using some other postgres server, I'm happy to try that.

**Comment by rbjarnason** [comment]
@Synaccord When we have deployed to Heroku we have staged a database locally then restored it with the Heroku Postgres command-line tools. But you can also set the FORCE_DB_SYNC env variable using heroku config:set, this will cause the models to be created and synced but we recommend unsetting this after initial creation as you'll want to run controlled db migrations when upgrading the production server in the future. See here: https://github.com/CitizensFoundation/your-priorities-app/blob/master/server_api/models/index.js#L62

**Comment by Synaccord** [comment]
That worked! I set FORCE_DB_SYNC to true, and then ran node server_api/scripts/setAdminOnAll.js me@email.com and then the app was running (but the script didn't seem to complete). And yes then I removed it.   Thanks.
