### ISSUE TITLE
Problem with image uploading

### ISSUE THREAD

**Issue by MarceMMAD** [CitizensFoundation/your-priorities-app#4]
If I am not using AWS S3, .eg. running the server on localhost or a non AWS server, is it still possible to use the image uploading feature of the app? Or it was meant to be used with AWS S3 only?

I could not make the image uploading to work on any of these three scenarios: localhost, AWS EC2 instance without S3, and DigitalOcean Dropplet (cloud virtual machine).

The app stops immediately when I click on the UPLOAD button. And if I run 
`AWS_ACCESS_KEY_ID=XXX AWS_SECRET_ACCESS_KEY=XXX S3_BUCKET=my-test ./start`
It does not stop but I get a `InvalidAccessKeyId` server does not have those keys.

**Comment by rbjarnason** [comment]
Currently only S3 AWS image uploads are supported through the s3-uploader npm.  You could setup a fake s3 server that talks the same protocol, I have not tried this but should work https://github.com/jubos/fake-s3 Or as all the image upload code is in just this one class you could implement another upload option here: https://github.com/rbjarnason/your-priorities-app/blob/master/server_api/models/image.js#L233

**Comment by MarceMMAD** [comment]
Thanks rbjarnason, I ended up using a AWS S3 to make it work. The `imagemagick` package is required to used the s3-uploade

**Comment by rbjarnason** [comment]
I've added reference to imagemagick to the readme.
