### ISSUE TITLE
You do not have access! Error

### ISSUE THREAD

**Issue by alimumcu1077** [CitizensFoundation/your-priorities-app#58]
We have just install this application, after start and create new user(also add as admin node server_api/scripts/setAdminOnAll.js your@email.com).
after  we  login application  always get "You do not have access!" pop up error.

i have started app with this command:
DATABASE_URL=postgres://developmentuser:password@127.0.0.1:5432/developmentdb ENV=production DEBUG=your-priorities-app  SESSION_SECRET=secret DISABLE_FORCE_HTTPS=1 NODE_ENV=production node ./api_app.js

**Comment by alimumcu1077** [comment]
Also There  is any docker image ext for this application(https://github.com/CitizensFoundation/your-priorities-app)?

**Comment by rbjarnason** [comment]
Hi @alimumcu1077 - I know, a very late answer to this ticket but we have recently created docker-compose based installation for Your Priorities, see here: https://github.com/CitizensFoundation/your-priorities-app/tree/master/deployment
