### ISSUE TITLE
Email notification doubts

### ISSUE THREAD

**Issue by MarceMMAD** [CitizensFoundation/your-priorities-app#6]
Hello @rbjarnason, how are you?, I have some questions about the email notification feateure of the app.

In order to send notifications by email, I see that the templates are within the active citizen and the email configuration parameters in the workers/email.js file. Am I right?

It is currently implemented for sendgrid email service. Would it work for an email account as well?
Does the `start` script, in the root folder, is all what I need to run to activate the notifications by email or do I need to run and/or configure something else from activice citizen?

**Comment by rbjarnason** [comment]
Hi @MarceMMAD :)

We're using https://github.com/nodemailer/nodemailer for the transport and that supports many different providers.  Yes, this is in workers/email.js

You need to run the Active Citizen main worker as well in server_api/active-citizen/workers/main.js and have a Redis server running for the event queue as well as sessions.

I've been very busy the past fews days with big load-time and other performance improvements across all platforms :) This is mostly achieved by mastering the use of iron-list element in the app. There are also updates to the idea list pages and newsfeeds that are now grids. And finally, Active Citizen curated newsfeeds are now enabled by default for logged in users :) You will need to run a PredictionIO server for this to work properly but if there is no PredictionIO available Active Citizen will ignore it and still go on by random and selecting what is coming in from the notifications.  I will launch this new version to our servers tomorrow or Friday.

**Comment by rbjarnason** [comment]
@MarceMMAD I'm closing this issue now, let me know if you need further information.
